spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_books?useSSL=false
    username: book-user
    password: book-pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG