INSERT INTO AUTHOR VALUES (1, 'Robert', 'Martin',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO AUTHOR VALUES (2, 'Gene', 'Kin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO AUTHOR VALUES (3, 'Kevin', 'Behr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO AUTHOR VALUES (4, 'George', 'Spafford', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BOOK VALUES (1, 'Clean Code: A Handbook of Agile Software Craftsmanship', 1, 18.45, '2013-01-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BOOK VALUES (2, 'The Phoenix Project: A Novel about IT, DevOps, and Helping Your Business Win', 1, 30.29, '2008-08-11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO AUTHOR_BOOK VALUES (1, 1);
INSERT INTO AUTHOR_BOOK VALUES (2, 2);
INSERT INTO AUTHOR_BOOK VALUES (2, 3);
INSERT INTO AUTHOR_BOOK VALUES (2, 4);